openapi: 3.0.0
info:
  title: API de Gestión de Productos
  version: 1.0.0
  description: API para la gestión de productos
tags:
  - name: Product
    description: API de gestión de productos
paths:
  /products:
    get:
      summary: Obtiene todos los productos
      tags:
        - Product
      responses:
        '200':
          description: Respuesta exitosa
        '500':
          description: Error interno del servidor

    post:
      summary: Agrega un nuevo producto
      tags:
        - Product
      responses:
        '200':
          description: Producto agregado exitosamente
        '500':
          description: Error interno del servidor

  /products/{pid}:
    get:
      summary: Obtiene un producto por su ID
      tags:
        - Product
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '200':
          description: Respuesta exitosa
        '500':
          description: Error interno del servidor

    put:
      summary: Actualiza un producto existente
      tags:
        - Product
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '200':
          description: Producto actualizado exitosamente
        '500':
          description: Error interno del servidor

    delete:
      summary: Elimina un producto existente
      tags:
        - Product
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '200':
          description: Producto eliminado exitosamente
        '500':
          description: Error interno del servidor
