openapi: 3.0.0
info:
  title: API de Gestión de Carritos
  version: 1.0.0
  description: API para la gestión de carritos de compra
tags:
  - name: Cart
    description: API de gestión de carritos
paths:
  /carts:
    post:
      summary: Crea un nuevo carrito
      tags:
        - Cart
      responses:
        '200':
          description: Carrito creado exitosamente
        '500':
          description: Error interno del servidor

  /carts/{cartId}:
    get:
      summary: Obtiene un carrito por su ID
      tags:
        - Cart
      parameters:
        - in: path
          name: cartId
          required: true
          description: ID del carrito
          schema:
            type: string
      responses:
        '200':
          description: Respuesta exitosa
        '500':
          description: Error interno del servidor

  /carts/products/{cartId}/product/{productId}:
    post:
      summary: Agrega un producto al carrito
      tags:
        - Cart
      parameters:
        - in: path
          name: cartId
          required: true
          description: ID del carrito
          schema:
            type: string
        - in: path
          name: productId
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '200':
          description: Producto agregado al carrito exitosamente
        '500':
          description: Error interno del servidor

    delete:
      summary: Elimina un producto del carrito
      tags:
        - Cart
      parameters:
        - in: path
          name: cartId
          required: true
          description: ID del carrito
          schema:
            type: string
        - in: path
          name: productId
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '200':
          description: Producto eliminado del carrito exitosamente
        '500':
          description: Error interno del servidor

    put:
      summary: Actualiza la cantidad de un producto en el carrito
      tags:
        - Cart
      parameters:
        - in: path
          name: cartId
          required: true
          description: ID del carrito
          schema:
            type: string
        - in: path
          name: productId
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '200':
          description: Cantidad de producto actualizada exitosamente
        '500':
          description: Error interno del servidor

  /carts/{cartId}:
    delete:
      summary: Vacía un carrito
      tags:
        - Cart
      parameters:
        - in: path
          name: cartId
          required: true
          description: ID del carrito
          schema:
            type: string
      responses:
        '200':
          description: Carrito vaciado exitosamente
        '500':
          description: Error interno del servidor

  /carts/{cartId}/purchase:
    post:
      summary: Realiza la compra de un carrito
      tags:
        - Cart
      parameters:
        - in: path
          name: cartId
          required: true
          description: ID del carrito
          schema:
            type: string
      responses:
        '200':
          description: Compra realizada exitosamente
        '500':
          description: Error interno del servidor
